{% set name = "xeus-r" %}

{% set version = "0.3.0" %}
{% set sha256 = "f0b4308b5a9ec1e3acf8f31fb20897f3814cfea2403be5ad79fe2617652a963c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/jupyter-xeus/xeus-r/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [unix]
  host:
    - xeus >=5
    - xeus-zmq >=3.0,<4.0
    - nlohmann_json >=3.11.3,<4
    - r-base
  run:
    - r-base
    - r-evaluate
    - r-jsonlite
    - r-glue
    - r-cli
    - r-repr
    - r-IRdisplay

test:
  commands:
    - test -f ${PREFIX}/bin/xr                                                              # [unix]
    - test -f ${PREFIX}/share/jupyter/kernels/xr/kernel.json                                # [unix]
    - test -d ${PREFIX}/include/xeus-r                                                      # [unix]
    - test -f ${PREFIX}/include/xeus-r/xinterpreter.hpp                                     # [unix]
    - test -f ${PREFIX}/lib/cmake/xeus-r/xeus-rConfig.cmake                                 # [unix]
    - test -f ${PREFIX}/lib/cmake/xeus-r/xeus-rConfigVersion.cmake                          # [unix]

    - if not exist %LIBRARY_BIN%\\xr.exe (exit 1)                                           # [win]
    - if not exist %LIBRARY_PREFIX%\\share\\jupyter\\kernels\\xr\\kernel.json (exit 1)      # [win]
    - if not exist %LIBRARY_LIB%\\cmake\\xeus-r\\xeus-rConfig.cmake (exit 1)                # [win]
    - if not exist %LIBRARY_LIB%\\cmake\\xeus-r\\xeus-rConfigVersion.cmake (exit 1)         # [win]
    # The kernel spec in installed in the general PREFIX
    - if not exist %PREFIX%\\share\\jupyter\\kernels\\xr\\kernel.json (exit 1)              # [win]


about:
  home: https://github.com/jupyter-xeus/xeus-r
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: R kernel for Jupyter based on xeus
  description: Jupyter kernel for the R programming language
  doc_url: https://github.com/jupyter-xeus/xeus-r
  dev_url: https://github.com/jupyter-xeus/xeus-r

extra:
  recipe-maintainers:
    - JohanMabille
    - DerThorsten
    - SylvainCorlay
    - romainfrancois
